FROM rust:1.76-slim as builder

WORKDIR /usr/src/app
COPY . .

RUN cargo build --release

FROM debian:bookworm-slim

COPY --from=builder /usr/src/app/target/release/backend /usr/local/bin/

CMD ["backend"]