FROM oven/bun:1 as builder

WORKDIR /app
COPY . .

RUN bun install
RUN bun run build

FROM node:20-slim

WORKDIR /app
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json .

RUN npm install -g serve

CMD ["serve", "-s", "build", "-l", "1420"]